// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlatformType.proto

package com.yzh.rfid.app.request;

public final class PlatformTypes {
  private PlatformTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PlatformType}
   */
  public enum PlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>iPhone = 0;</code>
     */
    iPhone(0),
    /**
     * <code>AndroidPhone = 1;</code>
     */
    AndroidPhone(1),
    /**
     * <code>Web = 2;</code>
     */
    Web(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>iPhone = 0;</code>
     */
    public static final int iPhone_VALUE = 0;
    /**
     * <code>AndroidPhone = 1;</code>
     */
    public static final int AndroidPhone_VALUE = 1;
    /**
     * <code>Web = 2;</code>
     */
    public static final int Web_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PlatformType valueOf(int value) {
      return forNumber(value);
    }

    public static PlatformType forNumber(int value) {
      switch (value) {
        case 0: return iPhone;
        case 1: return AndroidPhone;
        case 2: return Web;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
            public PlatformType findValueByNumber(int number) {
              return PlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PlatformTypes.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlatformType[] VALUES = values();

    public static PlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PlatformType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022PlatformType.proto*5\n\014PlatformType\022\n\n\006" +
      "iPhone\020\000\022\020\n\014AndroidPhone\020\001\022\007\n\003Web\020\002B-\n\034c" +
      "om.yzh.rfidbike.app.requestB\rPlatformTyp" +
      "esb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
