// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckUpdateResponse.proto

package com.yzh.rfid.app.response;

public final class CheckUpdateResponse {
  private CheckUpdateResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckUpdateResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckUpdateResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional string version = 2;</code>
     */
    String getVersion();
    /**
     * <code>optional string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional int64 updateTime = 3;</code>
     */
    long getUpdateTime();

    /**
     * <code>optional string updateLog = 4;</code>
     */
    String getUpdateLog();
    /**
     * <code>optional string updateLog = 4;</code>
     */
    com.google.protobuf.ByteString
        getUpdateLogBytes();

    /**
     * <code>optional string updateURL = 5;</code>
     */
    String getUpdateURL();
    /**
     * <code>optional string updateURL = 5;</code>
     */
    com.google.protobuf.ByteString
        getUpdateURLBytes();
  }
  /**
   * Protobuf type {@code CheckUpdateResponseMessage}
   */
  public  static final class CheckUpdateResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckUpdateResponseMessage)
      CheckUpdateResponseMessageOrBuilder {
    // Use CheckUpdateResponseMessage.newBuilder() to construct.
    private CheckUpdateResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckUpdateResponseMessage() {
      version_ = "";
      updateTime_ = 0L;
      updateLog_ = "";
      updateURL_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CheckUpdateResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 24: {

              updateTime_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              updateLog_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              updateURL_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.CheckUpdateResponse.internal_static_CheckUpdateResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.CheckUpdateResponse.internal_static_CheckUpdateResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.class, com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.Builder.class);
    }

    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile Object version_;
    /**
     * <code>optional string version = 2;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATETIME_FIELD_NUMBER = 3;
    private long updateTime_;
    /**
     * <code>optional int64 updateTime = 3;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    public static final int UPDATELOG_FIELD_NUMBER = 4;
    private volatile Object updateLog_;
    /**
     * <code>optional string updateLog = 4;</code>
     */
    public String getUpdateLog() {
      Object ref = updateLog_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateLog_ = s;
        return s;
      }
    }
    /**
     * <code>optional string updateLog = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateLogBytes() {
      Object ref = updateLog_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateLog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEURL_FIELD_NUMBER = 5;
    private volatile Object updateURL_;
    /**
     * <code>optional string updateURL = 5;</code>
     */
    public String getUpdateURL() {
      Object ref = updateURL_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateURL_ = s;
        return s;
      }
    }
    /**
     * <code>optional string updateURL = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateURLBytes() {
      Object ref = updateURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(3, updateTime_);
      }
      if (!getUpdateLogBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, updateLog_);
      }
      if (!getUpdateURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, updateURL_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, updateTime_);
      }
      if (!getUpdateLogBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, updateLog_);
      }
      if (!getUpdateURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, updateURL_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage other = (com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getUpdateTime()
          == other.getUpdateTime());
      result = result && getUpdateLog()
          .equals(other.getUpdateLog());
      result = result && getUpdateURL()
          .equals(other.getUpdateURL());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (37 * hash) + UPDATELOG_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateLog().hashCode();
      hash = (37 * hash) + UPDATEURL_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateURL().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckUpdateResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckUpdateResponseMessage)
        com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.CheckUpdateResponse.internal_static_CheckUpdateResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.CheckUpdateResponse.internal_static_CheckUpdateResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.class, com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        version_ = "";

        updateTime_ = 0L;

        updateLog_ = "";

        updateURL_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.CheckUpdateResponse.internal_static_CheckUpdateResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage build() {
        com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage buildPartial() {
        com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage result = new com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage(this);
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.version_ = version_;
        result.updateTime_ = updateTime_;
        result.updateLog_ = updateLog_;
        result.updateURL_ = updateURL_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage other) {
        if (other == com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        if (!other.getUpdateLog().isEmpty()) {
          updateLog_ = other.updateLog_;
          onChanged();
        }
        if (!other.getUpdateURL().isEmpty()) {
          updateURL_ = other.updateURL_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private Object version_ = "";
      /**
       * <code>optional string version = 2;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <code>optional int64 updateTime = 3;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>optional int64 updateTime = 3;</code>
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 updateTime = 3;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      private Object updateLog_ = "";
      /**
       * <code>optional string updateLog = 4;</code>
       */
      public String getUpdateLog() {
        Object ref = updateLog_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateLog_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string updateLog = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateLogBytes() {
        Object ref = updateLog_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateLog_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string updateLog = 4;</code>
       */
      public Builder setUpdateLog(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateLog_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateLog = 4;</code>
       */
      public Builder clearUpdateLog() {
        
        updateLog_ = getDefaultInstance().getUpdateLog();
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateLog = 4;</code>
       */
      public Builder setUpdateLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateLog_ = value;
        onChanged();
        return this;
      }

      private Object updateURL_ = "";
      /**
       * <code>optional string updateURL = 5;</code>
       */
      public String getUpdateURL() {
        Object ref = updateURL_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateURL_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string updateURL = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateURLBytes() {
        Object ref = updateURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string updateURL = 5;</code>
       */
      public Builder setUpdateURL(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateURL = 5;</code>
       */
      public Builder clearUpdateURL() {
        
        updateURL_ = getDefaultInstance().getUpdateURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateURL = 5;</code>
       */
      public Builder setUpdateURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateURL_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CheckUpdateResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:CheckUpdateResponseMessage)
    private static final com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage();
    }

    public static com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckUpdateResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<CheckUpdateResponseMessage>() {
      public CheckUpdateResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CheckUpdateResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckUpdateResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CheckUpdateResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.CheckUpdateResponse.CheckUpdateResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckUpdateResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckUpdateResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031CheckUpdateResponse.proto\032\032ErrorMessag" +
      "eResponse.proto\"\210\001\n\032CheckUpdateResponseM" +
      "essage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMessage\022" +
      "\017\n\007version\030\002 \001(\t\022\022\n\nupdateTime\030\003 \001(\003\022\021\n\t" +
      "updateLog\030\004 \001(\t\022\021\n\tupdateURL\030\005 \001(\tB4\n\035co" +
      "m.yzh.rfid.app.responseB\023CheckUpdate" +
      "Responseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
        }, assigner);
    internal_static_CheckUpdateResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckUpdateResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckUpdateResponseMessage_descriptor,
        new String[] { "ErrorMsg", "Version", "UpdateTime", "UpdateLog", "UpdateURL", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
