// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetAlarmMessageResponse.proto

package com.yzh.rfid.app.response;

public final class GetAlarmMessageResponse {
  private GetAlarmMessageResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetAlarmMessageResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetAlarmMessageResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional string isLastPage = 2;</code>
     */
    String getIsLastPage();
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    com.google.protobuf.ByteString
        getIsLastPageBytes();

    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> 
        getAlarmMessageList();
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage getAlarmMessage(int index);
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    int getAlarmMessageCount();
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder> 
        getAlarmMessageOrBuilderList();
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder getAlarmMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetAlarmMessageResponseMessage}
   */
  public  static final class GetAlarmMessageResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetAlarmMessageResponseMessage)
      GetAlarmMessageResponseMessageOrBuilder {
    // Use GetAlarmMessageResponseMessage.newBuilder() to construct.
    private GetAlarmMessageResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetAlarmMessageResponseMessage() {
      isLastPage_ = "";
      alarmMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetAlarmMessageResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              isLastPage_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                alarmMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              alarmMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          alarmMessage_ = java.util.Collections.unmodifiableList(alarmMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetAlarmMessageResponse.internal_static_GetAlarmMessageResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetAlarmMessageResponse.internal_static_GetAlarmMessageResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.class, com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int ISLASTPAGE_FIELD_NUMBER = 2;
    private volatile Object isLastPage_;
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public String getIsLastPage() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        isLastPage_ = s;
        return s;
      }
    }
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIsLastPageBytes() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        isLastPage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALARMMESSAGE_FIELD_NUMBER = 3;
    private java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> alarmMessage_;
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> getAlarmMessageList() {
      return alarmMessage_;
    }
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder> 
        getAlarmMessageOrBuilderList() {
      return alarmMessage_;
    }
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    public int getAlarmMessageCount() {
      return alarmMessage_.size();
    }
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage getAlarmMessage(int index) {
      return alarmMessage_.get(index);
    }
    /**
     * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
     */
    public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder getAlarmMessageOrBuilder(
        int index) {
      return alarmMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isLastPage_);
      }
      for (int i = 0; i < alarmMessage_.size(); i++) {
        output.writeMessage(3, alarmMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isLastPage_);
      }
      for (int i = 0; i < alarmMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, alarmMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage other = (com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getIsLastPage()
          .equals(other.getIsLastPage());
      result = result && getAlarmMessageList()
          .equals(other.getAlarmMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + ISLASTPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getIsLastPage().hashCode();
      if (getAlarmMessageCount() > 0) {
        hash = (37 * hash) + ALARMMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getAlarmMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetAlarmMessageResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetAlarmMessageResponseMessage)
        com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetAlarmMessageResponse.internal_static_GetAlarmMessageResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetAlarmMessageResponse.internal_static_GetAlarmMessageResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.class, com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAlarmMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        isLastPage_ = "";

        if (alarmMessageBuilder_ == null) {
          alarmMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          alarmMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetAlarmMessageResponse.internal_static_GetAlarmMessageResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage build() {
        com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage result = new com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.isLastPage_ = isLastPage_;
        if (alarmMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            alarmMessage_ = java.util.Collections.unmodifiableList(alarmMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.alarmMessage_ = alarmMessage_;
        } else {
          result.alarmMessage_ = alarmMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (!other.getIsLastPage().isEmpty()) {
          isLastPage_ = other.isLastPage_;
          onChanged();
        }
        if (alarmMessageBuilder_ == null) {
          if (!other.alarmMessage_.isEmpty()) {
            if (alarmMessage_.isEmpty()) {
              alarmMessage_ = other.alarmMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAlarmMessageIsMutable();
              alarmMessage_.addAll(other.alarmMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.alarmMessage_.isEmpty()) {
            if (alarmMessageBuilder_.isEmpty()) {
              alarmMessageBuilder_.dispose();
              alarmMessageBuilder_ = null;
              alarmMessage_ = other.alarmMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              alarmMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAlarmMessageFieldBuilder() : null;
            } else {
              alarmMessageBuilder_.addAllMessages(other.alarmMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private Object isLastPage_ = "";
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public String getIsLastPage() {
        Object ref = isLastPage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          isLastPage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIsLastPageBytes() {
        Object ref = isLastPage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          isLastPage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isLastPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder clearIsLastPage() {
        
        isLastPage_ = getDefaultInstance().getIsLastPage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isLastPage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> alarmMessage_ =
        java.util.Collections.emptyList();
      private void ensureAlarmMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          alarmMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage>(alarmMessage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder> alarmMessageBuilder_;

      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> getAlarmMessageList() {
        if (alarmMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alarmMessage_);
        } else {
          return alarmMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public int getAlarmMessageCount() {
        if (alarmMessageBuilder_ == null) {
          return alarmMessage_.size();
        } else {
          return alarmMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage getAlarmMessage(int index) {
        if (alarmMessageBuilder_ == null) {
          return alarmMessage_.get(index);
        } else {
          return alarmMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder setAlarmMessage(
          int index, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage value) {
        if (alarmMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmMessageIsMutable();
          alarmMessage_.set(index, value);
          onChanged();
        } else {
          alarmMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder setAlarmMessage(
          int index, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder builderForValue) {
        if (alarmMessageBuilder_ == null) {
          ensureAlarmMessageIsMutable();
          alarmMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          alarmMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder addAlarmMessage(com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage value) {
        if (alarmMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmMessageIsMutable();
          alarmMessage_.add(value);
          onChanged();
        } else {
          alarmMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder addAlarmMessage(
          int index, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage value) {
        if (alarmMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmMessageIsMutable();
          alarmMessage_.add(index, value);
          onChanged();
        } else {
          alarmMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder addAlarmMessage(
          com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder builderForValue) {
        if (alarmMessageBuilder_ == null) {
          ensureAlarmMessageIsMutable();
          alarmMessage_.add(builderForValue.build());
          onChanged();
        } else {
          alarmMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder addAlarmMessage(
          int index, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder builderForValue) {
        if (alarmMessageBuilder_ == null) {
          ensureAlarmMessageIsMutable();
          alarmMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          alarmMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder addAllAlarmMessage(
          Iterable<? extends com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage> values) {
        if (alarmMessageBuilder_ == null) {
          ensureAlarmMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, alarmMessage_);
          onChanged();
        } else {
          alarmMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder clearAlarmMessage() {
        if (alarmMessageBuilder_ == null) {
          alarmMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          alarmMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public Builder removeAlarmMessage(int index) {
        if (alarmMessageBuilder_ == null) {
          ensureAlarmMessageIsMutable();
          alarmMessage_.remove(index);
          onChanged();
        } else {
          alarmMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder getAlarmMessageBuilder(
          int index) {
        return getAlarmMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder getAlarmMessageOrBuilder(
          int index) {
        if (alarmMessageBuilder_ == null) {
          return alarmMessage_.get(index);  } else {
          return alarmMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder> 
           getAlarmMessageOrBuilderList() {
        if (alarmMessageBuilder_ != null) {
          return alarmMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alarmMessage_);
        }
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder addAlarmMessageBuilder() {
        return getAlarmMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder addAlarmMessageBuilder(
          int index) {
        return getAlarmMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .AlarmMessageMessage alarmMessage = 3;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder> 
           getAlarmMessageBuilderList() {
        return getAlarmMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder> 
          getAlarmMessageFieldBuilder() {
        if (alarmMessageBuilder_ == null) {
          alarmMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessage.Builder, com.yzh.rfid.app.response.AlarmMessage.AlarmMessageMessageOrBuilder>(
                  alarmMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          alarmMessage_ = null;
        }
        return alarmMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetAlarmMessageResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetAlarmMessageResponseMessage)
    private static final com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAlarmMessageResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetAlarmMessageResponseMessage>() {
      public GetAlarmMessageResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetAlarmMessageResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetAlarmMessageResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetAlarmMessageResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetAlarmMessageResponse.GetAlarmMessageResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAlarmMessageResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAlarmMessageResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035GetAlarmMessageResponse.proto\032\032ErrorMe" +
      "ssageResponse.proto\032\022AlarmMessage.proto\"" +
      "\201\001\n\036GetAlarmMessageResponseMessage\022\037\n\010er" +
      "rorMsg\030\001 \001(\0132\r.ErrorMessage\022\022\n\nisLastPag" +
      "e\030\002 \001(\t\022*\n\014alarmMessage\030\003 \003(\0132\024.AlarmMes" +
      "sageMessageB8\n\035com.yzh.rfid.app.resp" +
      "onseB\027GetAlarmMessageResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.AlarmMessage.getDescriptor(),
        }, assigner);
    internal_static_GetAlarmMessageResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetAlarmMessageResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAlarmMessageResponseMessage_descriptor,
        new String[] { "ErrorMsg", "IsLastPage", "AlarmMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.AlarmMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
