// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetCompanyListResponse.proto

package com.yzh.rfid.app.response;

public final class GetCompanyListResponse {
  private GetCompanyListResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCompanyListResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCompanyListResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage> 
        getCompanyMessageList();
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Company.CompanyMessage getCompanyMessage(int index);
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    int getCompanyMessageCount();
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder> 
        getCompanyMessageOrBuilderList();
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder getCompanyMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetCompanyListResponseMessage}
   */
  public  static final class GetCompanyListResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCompanyListResponseMessage)
      GetCompanyListResponseMessageOrBuilder {
    // Use GetCompanyListResponseMessage.newBuilder() to construct.
    private GetCompanyListResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCompanyListResponseMessage() {
      companyMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetCompanyListResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                companyMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.Company.CompanyMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              companyMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.Company.CompanyMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          companyMessage_ = java.util.Collections.unmodifiableList(companyMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetCompanyListResponse.internal_static_GetCompanyListResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetCompanyListResponse.internal_static_GetCompanyListResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.class, com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int COMPANYMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage> companyMessage_;
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage> getCompanyMessageList() {
      return companyMessage_;
    }
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder> 
        getCompanyMessageOrBuilderList() {
      return companyMessage_;
    }
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    public int getCompanyMessageCount() {
      return companyMessage_.size();
    }
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Company.CompanyMessage getCompanyMessage(int index) {
      return companyMessage_.get(index);
    }
    /**
     * <code>repeated .CompanyMessage companyMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder getCompanyMessageOrBuilder(
        int index) {
      return companyMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < companyMessage_.size(); i++) {
        output.writeMessage(2, companyMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < companyMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, companyMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage other = (com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getCompanyMessageList()
          .equals(other.getCompanyMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getCompanyMessageCount() > 0) {
        hash = (37 * hash) + COMPANYMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCompanyMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCompanyListResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCompanyListResponseMessage)
        com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetCompanyListResponse.internal_static_GetCompanyListResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetCompanyListResponse.internal_static_GetCompanyListResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.class, com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCompanyMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (companyMessageBuilder_ == null) {
          companyMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          companyMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetCompanyListResponse.internal_static_GetCompanyListResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage build() {
        com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage result = new com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (companyMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            companyMessage_ = java.util.Collections.unmodifiableList(companyMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.companyMessage_ = companyMessage_;
        } else {
          result.companyMessage_ = companyMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (companyMessageBuilder_ == null) {
          if (!other.companyMessage_.isEmpty()) {
            if (companyMessage_.isEmpty()) {
              companyMessage_ = other.companyMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCompanyMessageIsMutable();
              companyMessage_.addAll(other.companyMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.companyMessage_.isEmpty()) {
            if (companyMessageBuilder_.isEmpty()) {
              companyMessageBuilder_.dispose();
              companyMessageBuilder_ = null;
              companyMessage_ = other.companyMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              companyMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCompanyMessageFieldBuilder() : null;
            } else {
              companyMessageBuilder_.addAllMessages(other.companyMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage> companyMessage_ =
        java.util.Collections.emptyList();
      private void ensureCompanyMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          companyMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.Company.CompanyMessage>(companyMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Company.CompanyMessage, com.yzh.rfid.app.response.Company.CompanyMessage.Builder, com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder> companyMessageBuilder_;

      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage> getCompanyMessageList() {
        if (companyMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(companyMessage_);
        } else {
          return companyMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public int getCompanyMessageCount() {
        if (companyMessageBuilder_ == null) {
          return companyMessage_.size();
        } else {
          return companyMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Company.CompanyMessage getCompanyMessage(int index) {
        if (companyMessageBuilder_ == null) {
          return companyMessage_.get(index);
        } else {
          return companyMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder setCompanyMessage(
          int index, com.yzh.rfid.app.response.Company.CompanyMessage value) {
        if (companyMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanyMessageIsMutable();
          companyMessage_.set(index, value);
          onChanged();
        } else {
          companyMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder setCompanyMessage(
          int index, com.yzh.rfid.app.response.Company.CompanyMessage.Builder builderForValue) {
        if (companyMessageBuilder_ == null) {
          ensureCompanyMessageIsMutable();
          companyMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          companyMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder addCompanyMessage(com.yzh.rfid.app.response.Company.CompanyMessage value) {
        if (companyMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanyMessageIsMutable();
          companyMessage_.add(value);
          onChanged();
        } else {
          companyMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder addCompanyMessage(
          int index, com.yzh.rfid.app.response.Company.CompanyMessage value) {
        if (companyMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanyMessageIsMutable();
          companyMessage_.add(index, value);
          onChanged();
        } else {
          companyMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder addCompanyMessage(
          com.yzh.rfid.app.response.Company.CompanyMessage.Builder builderForValue) {
        if (companyMessageBuilder_ == null) {
          ensureCompanyMessageIsMutable();
          companyMessage_.add(builderForValue.build());
          onChanged();
        } else {
          companyMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder addCompanyMessage(
          int index, com.yzh.rfid.app.response.Company.CompanyMessage.Builder builderForValue) {
        if (companyMessageBuilder_ == null) {
          ensureCompanyMessageIsMutable();
          companyMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          companyMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder addAllCompanyMessage(
          Iterable<? extends com.yzh.rfid.app.response.Company.CompanyMessage> values) {
        if (companyMessageBuilder_ == null) {
          ensureCompanyMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, companyMessage_);
          onChanged();
        } else {
          companyMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder clearCompanyMessage() {
        if (companyMessageBuilder_ == null) {
          companyMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          companyMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public Builder removeCompanyMessage(int index) {
        if (companyMessageBuilder_ == null) {
          ensureCompanyMessageIsMutable();
          companyMessage_.remove(index);
          onChanged();
        } else {
          companyMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Company.CompanyMessage.Builder getCompanyMessageBuilder(
          int index) {
        return getCompanyMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder getCompanyMessageOrBuilder(
          int index) {
        if (companyMessageBuilder_ == null) {
          return companyMessage_.get(index);  } else {
          return companyMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder> 
           getCompanyMessageOrBuilderList() {
        if (companyMessageBuilder_ != null) {
          return companyMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(companyMessage_);
        }
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Company.CompanyMessage.Builder addCompanyMessageBuilder() {
        return getCompanyMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.Company.CompanyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.Company.CompanyMessage.Builder addCompanyMessageBuilder(
          int index) {
        return getCompanyMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.Company.CompanyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .CompanyMessage companyMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.Company.CompanyMessage.Builder> 
           getCompanyMessageBuilderList() {
        return getCompanyMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.Company.CompanyMessage, com.yzh.rfid.app.response.Company.CompanyMessage.Builder, com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder> 
          getCompanyMessageFieldBuilder() {
        if (companyMessageBuilder_ == null) {
          companyMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.Company.CompanyMessage, com.yzh.rfid.app.response.Company.CompanyMessage.Builder, com.yzh.rfid.app.response.Company.CompanyMessageOrBuilder>(
                  companyMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          companyMessage_ = null;
        }
        return companyMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetCompanyListResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetCompanyListResponseMessage)
    private static final com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCompanyListResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetCompanyListResponseMessage>() {
      public GetCompanyListResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetCompanyListResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCompanyListResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetCompanyListResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetCompanyListResponse.GetCompanyListResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompanyListResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompanyListResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034GetCompanyListResponse.proto\032\032ErrorMes" +
      "sageResponse.proto\032\rCompany.proto\"i\n\035Get" +
      "CompanyListResponseMessage\022\037\n\010errorMsg\030\001" +
      " \001(\0132\r.ErrorMessage\022\'\n\016companyMessage\030\002 " +
      "\003(\0132\017.CompanyMessageB7\n\035com.yzh.rfid" +
      ".app.responseB\026GetCompanyListResponseb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.Company.getDescriptor(),
        }, assigner);
    internal_static_GetCompanyListResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCompanyListResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompanyListResponseMessage_descriptor,
        new String[] { "ErrorMsg", "CompanyMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.Company.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
