// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetDeviceCountResponse.proto

package com.yzh.rfid.app.response;

public final class GetDeviceCountResponse {
  private GetDeviceCountResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetDeviceCountResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetDeviceCountResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional int64 onLineCount = 2;</code>
     */
    long getOnLineCount();

    /**
     * <code>optional int64 offLineCount = 3;</code>
     */
    long getOffLineCount();

    /**
     * <code>optional int64 highTempCount = 4;</code>
     */
    long getHighTempCount();

    /**
     * <code>optional int64 lowBatteryCount = 5;</code>
     */
    long getLowBatteryCount();
  }
  /**
   * Protobuf type {@code GetDeviceCountResponseMessage}
   */
  public  static final class GetDeviceCountResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetDeviceCountResponseMessage)
      GetDeviceCountResponseMessageOrBuilder {
    // Use GetDeviceCountResponseMessage.newBuilder() to construct.
    private GetDeviceCountResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDeviceCountResponseMessage() {
      onLineCount_ = 0L;
      offLineCount_ = 0L;
      highTempCount_ = 0L;
      lowBatteryCount_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetDeviceCountResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              onLineCount_ = input.readInt64();
              break;
            }
            case 24: {

              offLineCount_ = input.readInt64();
              break;
            }
            case 32: {

              highTempCount_ = input.readInt64();
              break;
            }
            case 40: {

              lowBatteryCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetDeviceCountResponse.internal_static_GetDeviceCountResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetDeviceCountResponse.internal_static_GetDeviceCountResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.class, com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.Builder.class);
    }

    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int ONLINECOUNT_FIELD_NUMBER = 2;
    private long onLineCount_;
    /**
     * <code>optional int64 onLineCount = 2;</code>
     */
    public long getOnLineCount() {
      return onLineCount_;
    }

    public static final int OFFLINECOUNT_FIELD_NUMBER = 3;
    private long offLineCount_;
    /**
     * <code>optional int64 offLineCount = 3;</code>
     */
    public long getOffLineCount() {
      return offLineCount_;
    }

    public static final int HIGHTEMPCOUNT_FIELD_NUMBER = 4;
    private long highTempCount_;
    /**
     * <code>optional int64 highTempCount = 4;</code>
     */
    public long getHighTempCount() {
      return highTempCount_;
    }

    public static final int LOWBATTERYCOUNT_FIELD_NUMBER = 5;
    private long lowBatteryCount_;
    /**
     * <code>optional int64 lowBatteryCount = 5;</code>
     */
    public long getLowBatteryCount() {
      return lowBatteryCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (onLineCount_ != 0L) {
        output.writeInt64(2, onLineCount_);
      }
      if (offLineCount_ != 0L) {
        output.writeInt64(3, offLineCount_);
      }
      if (highTempCount_ != 0L) {
        output.writeInt64(4, highTempCount_);
      }
      if (lowBatteryCount_ != 0L) {
        output.writeInt64(5, lowBatteryCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (onLineCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, onLineCount_);
      }
      if (offLineCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, offLineCount_);
      }
      if (highTempCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, highTempCount_);
      }
      if (lowBatteryCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lowBatteryCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage other = (com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && (getOnLineCount()
          == other.getOnLineCount());
      result = result && (getOffLineCount()
          == other.getOffLineCount());
      result = result && (getHighTempCount()
          == other.getHighTempCount());
      result = result && (getLowBatteryCount()
          == other.getLowBatteryCount());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + ONLINECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOnLineCount());
      hash = (37 * hash) + OFFLINECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffLineCount());
      hash = (37 * hash) + HIGHTEMPCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHighTempCount());
      hash = (37 * hash) + LOWBATTERYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLowBatteryCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetDeviceCountResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetDeviceCountResponseMessage)
        com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetDeviceCountResponse.internal_static_GetDeviceCountResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetDeviceCountResponse.internal_static_GetDeviceCountResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.class, com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        onLineCount_ = 0L;

        offLineCount_ = 0L;

        highTempCount_ = 0L;

        lowBatteryCount_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetDeviceCountResponse.internal_static_GetDeviceCountResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage build() {
        com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage result = new com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage(this);
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.onLineCount_ = onLineCount_;
        result.offLineCount_ = offLineCount_;
        result.highTempCount_ = highTempCount_;
        result.lowBatteryCount_ = lowBatteryCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (other.getOnLineCount() != 0L) {
          setOnLineCount(other.getOnLineCount());
        }
        if (other.getOffLineCount() != 0L) {
          setOffLineCount(other.getOffLineCount());
        }
        if (other.getHighTempCount() != 0L) {
          setHighTempCount(other.getHighTempCount());
        }
        if (other.getLowBatteryCount() != 0L) {
          setLowBatteryCount(other.getLowBatteryCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private long onLineCount_ ;
      /**
       * <code>optional int64 onLineCount = 2;</code>
       */
      public long getOnLineCount() {
        return onLineCount_;
      }
      /**
       * <code>optional int64 onLineCount = 2;</code>
       */
      public Builder setOnLineCount(long value) {
        
        onLineCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 onLineCount = 2;</code>
       */
      public Builder clearOnLineCount() {
        
        onLineCount_ = 0L;
        onChanged();
        return this;
      }

      private long offLineCount_ ;
      /**
       * <code>optional int64 offLineCount = 3;</code>
       */
      public long getOffLineCount() {
        return offLineCount_;
      }
      /**
       * <code>optional int64 offLineCount = 3;</code>
       */
      public Builder setOffLineCount(long value) {
        
        offLineCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 offLineCount = 3;</code>
       */
      public Builder clearOffLineCount() {
        
        offLineCount_ = 0L;
        onChanged();
        return this;
      }

      private long highTempCount_ ;
      /**
       * <code>optional int64 highTempCount = 4;</code>
       */
      public long getHighTempCount() {
        return highTempCount_;
      }
      /**
       * <code>optional int64 highTempCount = 4;</code>
       */
      public Builder setHighTempCount(long value) {
        
        highTempCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 highTempCount = 4;</code>
       */
      public Builder clearHighTempCount() {
        
        highTempCount_ = 0L;
        onChanged();
        return this;
      }

      private long lowBatteryCount_ ;
      /**
       * <code>optional int64 lowBatteryCount = 5;</code>
       */
      public long getLowBatteryCount() {
        return lowBatteryCount_;
      }
      /**
       * <code>optional int64 lowBatteryCount = 5;</code>
       */
      public Builder setLowBatteryCount(long value) {
        
        lowBatteryCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lowBatteryCount = 5;</code>
       */
      public Builder clearLowBatteryCount() {
        
        lowBatteryCount_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetDeviceCountResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetDeviceCountResponseMessage)
    private static final com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDeviceCountResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetDeviceCountResponseMessage>() {
      public GetDeviceCountResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetDeviceCountResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDeviceCountResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetDeviceCountResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetDeviceCountResponse.GetDeviceCountResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDeviceCountResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDeviceCountResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034GetDeviceCountResponse.proto\032\032ErrorMes" +
      "sageResponse.proto\"\233\001\n\035GetDeviceCountRes" +
      "ponseMessage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMe" +
      "ssage\022\023\n\013onLineCount\030\002 \001(\003\022\024\n\014offLineCou" +
      "nt\030\003 \001(\003\022\025\n\rhighTempCount\030\004 \001(\003\022\027\n\017lowBa" +
      "tteryCount\030\005 \001(\003B7\n\035com.yzh.rfid.app" +
      ".responseB\026GetDeviceCountResponseb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
        }, assigner);
    internal_static_GetDeviceCountResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetDeviceCountResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDeviceCountResponseMessage_descriptor,
        new String[] { "ErrorMsg", "OnLineCount", "OffLineCount", "HighTempCount", "LowBatteryCount", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
