// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetSystemMessageResponse.proto

package com.yzh.rfid.app.response;

public final class GetSystemMessageResponse {
  private GetSystemMessageResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetSystemMessageResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetSystemMessageResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional string isLastPage = 2;</code>
     */
    String getIsLastPage();
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    com.google.protobuf.ByteString
        getIsLastPageBytes();

    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> 
        getSystemMessageList();
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getSystemMessage(int index);
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    int getSystemMessageCount();
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder> 
        getSystemMessageOrBuilderList();
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder getSystemMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code GetSystemMessageResponseMessage}
   */
  public  static final class GetSystemMessageResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetSystemMessageResponseMessage)
      GetSystemMessageResponseMessageOrBuilder {
    // Use GetSystemMessageResponseMessage.newBuilder() to construct.
    private GetSystemMessageResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetSystemMessageResponseMessage() {
      isLastPage_ = "";
      systemMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetSystemMessageResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              isLastPage_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                systemMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              systemMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          systemMessage_ = java.util.Collections.unmodifiableList(systemMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.GetSystemMessageResponse.internal_static_GetSystemMessageResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.GetSystemMessageResponse.internal_static_GetSystemMessageResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.class, com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int ISLASTPAGE_FIELD_NUMBER = 2;
    private volatile Object isLastPage_;
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public String getIsLastPage() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        isLastPage_ = s;
        return s;
      }
    }
    /**
     * <code>optional string isLastPage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIsLastPageBytes() {
      Object ref = isLastPage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        isLastPage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEMMESSAGE_FIELD_NUMBER = 3;
    private java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> systemMessage_;
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> getSystemMessageList() {
      return systemMessage_;
    }
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder> 
        getSystemMessageOrBuilderList() {
      return systemMessage_;
    }
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    public int getSystemMessageCount() {
      return systemMessage_.size();
    }
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getSystemMessage(int index) {
      return systemMessage_.get(index);
    }
    /**
     * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
     */
    public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder getSystemMessageOrBuilder(
        int index) {
      return systemMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isLastPage_);
      }
      for (int i = 0; i < systemMessage_.size(); i++) {
        output.writeMessage(3, systemMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (!getIsLastPageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isLastPage_);
      }
      for (int i = 0; i < systemMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, systemMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage other = (com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getIsLastPage()
          .equals(other.getIsLastPage());
      result = result && getSystemMessageList()
          .equals(other.getSystemMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + ISLASTPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getIsLastPage().hashCode();
      if (getSystemMessageCount() > 0) {
        hash = (37 * hash) + SYSTEMMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSystemMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetSystemMessageResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetSystemMessageResponseMessage)
        com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.GetSystemMessageResponse.internal_static_GetSystemMessageResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.GetSystemMessageResponse.internal_static_GetSystemMessageResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.class, com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSystemMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        isLastPage_ = "";

        if (systemMessageBuilder_ == null) {
          systemMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          systemMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.GetSystemMessageResponse.internal_static_GetSystemMessageResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage build() {
        com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage buildPartial() {
        com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage result = new com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.isLastPage_ = isLastPage_;
        if (systemMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            systemMessage_ = java.util.Collections.unmodifiableList(systemMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.systemMessage_ = systemMessage_;
        } else {
          result.systemMessage_ = systemMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage other) {
        if (other == com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (!other.getIsLastPage().isEmpty()) {
          isLastPage_ = other.isLastPage_;
          onChanged();
        }
        if (systemMessageBuilder_ == null) {
          if (!other.systemMessage_.isEmpty()) {
            if (systemMessage_.isEmpty()) {
              systemMessage_ = other.systemMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSystemMessageIsMutable();
              systemMessage_.addAll(other.systemMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.systemMessage_.isEmpty()) {
            if (systemMessageBuilder_.isEmpty()) {
              systemMessageBuilder_.dispose();
              systemMessageBuilder_ = null;
              systemMessage_ = other.systemMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              systemMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSystemMessageFieldBuilder() : null;
            } else {
              systemMessageBuilder_.addAllMessages(other.systemMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private Object isLastPage_ = "";
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public String getIsLastPage() {
        Object ref = isLastPage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          isLastPage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIsLastPageBytes() {
        Object ref = isLastPage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          isLastPage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isLastPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder clearIsLastPage() {
        
        isLastPage_ = getDefaultInstance().getIsLastPage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string isLastPage = 2;</code>
       */
      public Builder setIsLastPageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isLastPage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> systemMessage_ =
        java.util.Collections.emptyList();
      private void ensureSystemMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          systemMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage>(systemMessage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder> systemMessageBuilder_;

      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> getSystemMessageList() {
        if (systemMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(systemMessage_);
        } else {
          return systemMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public int getSystemMessageCount() {
        if (systemMessageBuilder_ == null) {
          return systemMessage_.size();
        } else {
          return systemMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getSystemMessage(int index) {
        if (systemMessageBuilder_ == null) {
          return systemMessage_.get(index);
        } else {
          return systemMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder setSystemMessage(
          int index, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage value) {
        if (systemMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemMessageIsMutable();
          systemMessage_.set(index, value);
          onChanged();
        } else {
          systemMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder setSystemMessage(
          int index, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder builderForValue) {
        if (systemMessageBuilder_ == null) {
          ensureSystemMessageIsMutable();
          systemMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          systemMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder addSystemMessage(com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage value) {
        if (systemMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemMessageIsMutable();
          systemMessage_.add(value);
          onChanged();
        } else {
          systemMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder addSystemMessage(
          int index, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage value) {
        if (systemMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemMessageIsMutable();
          systemMessage_.add(index, value);
          onChanged();
        } else {
          systemMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder addSystemMessage(
          com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder builderForValue) {
        if (systemMessageBuilder_ == null) {
          ensureSystemMessageIsMutable();
          systemMessage_.add(builderForValue.build());
          onChanged();
        } else {
          systemMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder addSystemMessage(
          int index, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder builderForValue) {
        if (systemMessageBuilder_ == null) {
          ensureSystemMessageIsMutable();
          systemMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          systemMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder addAllSystemMessage(
          Iterable<? extends com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage> values) {
        if (systemMessageBuilder_ == null) {
          ensureSystemMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, systemMessage_);
          onChanged();
        } else {
          systemMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder clearSystemMessage() {
        if (systemMessageBuilder_ == null) {
          systemMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          systemMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public Builder removeSystemMessage(int index) {
        if (systemMessageBuilder_ == null) {
          ensureSystemMessageIsMutable();
          systemMessage_.remove(index);
          onChanged();
        } else {
          systemMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder getSystemMessageBuilder(
          int index) {
        return getSystemMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder getSystemMessageOrBuilder(
          int index) {
        if (systemMessageBuilder_ == null) {
          return systemMessage_.get(index);  } else {
          return systemMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder> 
           getSystemMessageOrBuilderList() {
        if (systemMessageBuilder_ != null) {
          return systemMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(systemMessage_);
        }
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder addSystemMessageBuilder() {
        return getSystemMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder addSystemMessageBuilder(
          int index) {
        return getSystemMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SystemMessageMessage systemMessage = 3;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder> 
           getSystemMessageBuilderList() {
        return getSystemMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder> 
          getSystemMessageFieldBuilder() {
        if (systemMessageBuilder_ == null) {
          systemMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder>(
                  systemMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          systemMessage_ = null;
        }
        return systemMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetSystemMessageResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:GetSystemMessageResponseMessage)
    private static final com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage();
    }

    public static com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSystemMessageResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetSystemMessageResponseMessage>() {
      public GetSystemMessageResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetSystemMessageResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetSystemMessageResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetSystemMessageResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.GetSystemMessageResponse.GetSystemMessageResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSystemMessageResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSystemMessageResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036GetSystemMessageResponse.proto\032\032ErrorM" +
      "essageResponse.proto\032\023SystemMessage.prot" +
      "o\"\204\001\n\037GetSystemMessageResponseMessage\022\037\n" +
      "\010errorMsg\030\001 \001(\0132\r.ErrorMessage\022\022\n\nisLast" +
      "Page\030\002 \001(\t\022,\n\rsystemMessage\030\003 \003(\0132\025.Syst" +
      "emMessageMessageB9\n\035com.yzh.rfid.app" +
      ".responseB\030GetSystemMessageResponseb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.SystemMessage.getDescriptor(),
        }, assigner);
    internal_static_GetSystemMessageResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetSystemMessageResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSystemMessageResponseMessage_descriptor,
        new String[] { "ErrorMsg", "IsLastPage", "SystemMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.SystemMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
