// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginResponse.proto

package com.yzh.rfid.app.response;

public final class LoginResponse {
  private LoginResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>optional string session = 2;</code>
     */
    String getSession();
    /**
     * <code>optional string session = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <code>optional int64 id = 3;</code>
     */
    long getId();

    /**
     * <code>optional int64 company_id = 4;</code>
     */
    long getCompanyId();

    /**
     * <code>optional int64 office_id = 5;</code>
     */
    long getOfficeId();

    /**
     * <code>optional string id_card = 6;</code>
     */
    String getIdCard();
    /**
     * <code>optional string id_card = 6;</code>
     */
    com.google.protobuf.ByteString
        getIdCardBytes();

    /**
     * <code>optional string id_front_pic_path = 7;</code>
     */
    String getIdFrontPicPath();
    /**
     * <code>optional string id_front_pic_path = 7;</code>
     */
    com.google.protobuf.ByteString
        getIdFrontPicPathBytes();

    /**
     * <code>optional string id_back_pic_path = 8;</code>
     */
    String getIdBackPicPath();
    /**
     * <code>optional string id_back_pic_path = 8;</code>
     */
    com.google.protobuf.ByteString
        getIdBackPicPathBytes();

    /**
     * <code>optional string password = 9;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 9;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string name = 10;</code>
     */
    String getName();
    /**
     * <code>optional string name = 10;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 11;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 11;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string phone = 12;</code>
     */
    String getPhone();
    /**
     * <code>optional string phone = 12;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>optional string mobile = 13;</code>
     */
    String getMobile();
    /**
     * <code>optional string mobile = 13;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>optional string address = 14;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 14;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional string photo = 15;</code>
     */
    String getPhoto();
    /**
     * <code>optional string photo = 15;</code>
     */
    com.google.protobuf.ByteString
        getPhotoBytes();

    /**
     * <code>optional int32 sex = 16;</code>
     */
    int getSex();

    /**
     * <code>optional int32 age = 17;</code>
     */
    int getAge();
  }
  /**
   * Protobuf type {@code LoginResponseMessage}
   */
  public  static final class LoginResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginResponseMessage)
      LoginResponseMessageOrBuilder {
    // Use LoginResponseMessage.newBuilder() to construct.
    private LoginResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponseMessage() {
      session_ = "";
      id_ = 0L;
      companyId_ = 0L;
      officeId_ = 0L;
      idCard_ = "";
      idFrontPicPath_ = "";
      idBackPicPath_ = "";
      password_ = "";
      name_ = "";
      email_ = "";
      phone_ = "";
      mobile_ = "";
      address_ = "";
      photo_ = "";
      sex_ = 0;
      age_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 24: {

              id_ = input.readInt64();
              break;
            }
            case 32: {

              companyId_ = input.readInt64();
              break;
            }
            case 40: {

              officeId_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              idCard_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              idFrontPicPath_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              idBackPicPath_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 122: {
              String s = input.readStringRequireUtf8();

              photo_ = s;
              break;
            }
            case 128: {

              sex_ = input.readInt32();
              break;
            }
            case 136: {

              age_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginResponse.internal_static_LoginResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginResponse.internal_static_LoginResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginResponseMessage.class, Builder.class);
    }

    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int SESSION_FIELD_NUMBER = 2;
    private volatile Object session_;
    /**
     * <code>optional string session = 2;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <code>optional string session = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private long id_;
    /**
     * <code>optional int64 id = 3;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 4;
    private long companyId_;
    /**
     * <code>optional int64 company_id = 4;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int OFFICE_ID_FIELD_NUMBER = 5;
    private long officeId_;
    /**
     * <code>optional int64 office_id = 5;</code>
     */
    public long getOfficeId() {
      return officeId_;
    }

    public static final int ID_CARD_FIELD_NUMBER = 6;
    private volatile Object idCard_;
    /**
     * <code>optional string id_card = 6;</code>
     */
    public String getIdCard() {
      Object ref = idCard_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idCard_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id_card = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdCardBytes() {
      Object ref = idCard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FRONT_PIC_PATH_FIELD_NUMBER = 7;
    private volatile Object idFrontPicPath_;
    /**
     * <code>optional string id_front_pic_path = 7;</code>
     */
    public String getIdFrontPicPath() {
      Object ref = idFrontPicPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idFrontPicPath_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id_front_pic_path = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIdFrontPicPathBytes() {
      Object ref = idFrontPicPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idFrontPicPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_BACK_PIC_PATH_FIELD_NUMBER = 8;
    private volatile Object idBackPicPath_;
    /**
     * <code>optional string id_back_pic_path = 8;</code>
     */
    public String getIdBackPicPath() {
      Object ref = idBackPicPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idBackPicPath_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id_back_pic_path = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIdBackPicPathBytes() {
      Object ref = idBackPicPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idBackPicPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 9;
    private volatile Object password_;
    /**
     * <code>optional string password = 9;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 10;
    private volatile Object name_;
    /**
     * <code>optional string name = 10;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 11;
    private volatile Object email_;
    /**
     * <code>optional string email = 11;</code>
     */
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 11;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 12;
    private volatile Object phone_;
    /**
     * <code>optional string phone = 12;</code>
     */
    public String getPhone() {
      Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phone = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 13;
    private volatile Object mobile_;
    /**
     * <code>optional string mobile = 13;</code>
     */
    public String getMobile() {
      Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mobile = 13;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 14;
    private volatile Object address_;
    /**
     * <code>optional string address = 14;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 14;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHOTO_FIELD_NUMBER = 15;
    private volatile Object photo_;
    /**
     * <code>optional string photo = 15;</code>
     */
    public String getPhoto() {
      Object ref = photo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        photo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string photo = 15;</code>
     */
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      Object ref = photo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        photo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 16;
    private int sex_;
    /**
     * <code>optional int32 sex = 16;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int AGE_FIELD_NUMBER = 17;
    private int age_;
    /**
     * <code>optional int32 age = 17;</code>
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, session_);
      }
      if (id_ != 0L) {
        output.writeInt64(3, id_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(4, companyId_);
      }
      if (officeId_ != 0L) {
        output.writeInt64(5, officeId_);
      }
      if (!getIdCardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, idCard_);
      }
      if (!getIdFrontPicPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, idFrontPicPath_);
      }
      if (!getIdBackPicPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, idBackPicPath_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, password_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, phone_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, mobile_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, address_);
      }
      if (!getPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, photo_);
      }
      if (sex_ != 0) {
        output.writeInt32(16, sex_);
      }
      if (age_ != 0) {
        output.writeInt32(17, age_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, session_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, id_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, companyId_);
      }
      if (officeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, officeId_);
      }
      if (!getIdCardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, idCard_);
      }
      if (!getIdFrontPicPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, idFrontPicPath_);
      }
      if (!getIdBackPicPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, idBackPicPath_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, password_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, phone_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, mobile_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, address_);
      }
      if (!getPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, photo_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, sex_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, age_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginResponseMessage)) {
        return super.equals(obj);
      }
      LoginResponseMessage other = (LoginResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getSession()
          .equals(other.getSession());
      result = result && (getId()
          == other.getId());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && (getOfficeId()
          == other.getOfficeId());
      result = result && getIdCard()
          .equals(other.getIdCard());
      result = result && getIdFrontPicPath()
          .equals(other.getIdFrontPicPath());
      result = result && getIdBackPicPath()
          .equals(other.getIdBackPicPath());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getPhone()
          .equals(other.getPhone());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPhoto()
          .equals(other.getPhoto());
      result = result && (getSex()
          == other.getSex());
      result = result && (getAge()
          == other.getAge());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCompanyId());
      hash = (37 * hash) + OFFICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOfficeId());
      hash = (37 * hash) + ID_CARD_FIELD_NUMBER;
      hash = (53 * hash) + getIdCard().hashCode();
      hash = (37 * hash) + ID_FRONT_PIC_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getIdFrontPicPath().hashCode();
      hash = (37 * hash) + ID_BACK_PIC_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getIdBackPicPath().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getPhoto().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResponseMessage)
        LoginResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginResponse.internal_static_LoginResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginResponse.internal_static_LoginResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginResponseMessage.class, Builder.class);
      }

      // Construct using com.yzh.rfidbike.app.response.LoginResponse.LoginResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        session_ = "";

        id_ = 0L;

        companyId_ = 0L;

        officeId_ = 0L;

        idCard_ = "";

        idFrontPicPath_ = "";

        idBackPicPath_ = "";

        password_ = "";

        name_ = "";

        email_ = "";

        phone_ = "";

        mobile_ = "";

        address_ = "";

        photo_ = "";

        sex_ = 0;

        age_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginResponse.internal_static_LoginResponseMessage_descriptor;
      }

      public LoginResponseMessage getDefaultInstanceForType() {
        return LoginResponseMessage.getDefaultInstance();
      }

      public LoginResponseMessage build() {
        LoginResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LoginResponseMessage buildPartial() {
        LoginResponseMessage result = new LoginResponseMessage(this);
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        result.session_ = session_;
        result.id_ = id_;
        result.companyId_ = companyId_;
        result.officeId_ = officeId_;
        result.idCard_ = idCard_;
        result.idFrontPicPath_ = idFrontPicPath_;
        result.idBackPicPath_ = idBackPicPath_;
        result.password_ = password_;
        result.name_ = name_;
        result.email_ = email_;
        result.phone_ = phone_;
        result.mobile_ = mobile_;
        result.address_ = address_;
        result.photo_ = photo_;
        result.sex_ = sex_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginResponseMessage) {
          return mergeFrom((LoginResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginResponseMessage other) {
        if (other == LoginResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getOfficeId() != 0L) {
          setOfficeId(other.getOfficeId());
        }
        if (!other.getIdCard().isEmpty()) {
          idCard_ = other.idCard_;
          onChanged();
        }
        if (!other.getIdFrontPicPath().isEmpty()) {
          idFrontPicPath_ = other.idFrontPicPath_;
          onChanged();
        }
        if (!other.getIdBackPicPath().isEmpty()) {
          idBackPicPath_ = other.idBackPicPath_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getPhoto().isEmpty()) {
          photo_ = other.photo_;
          onChanged();
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ErrorMessageResponse.ErrorMessage, ErrorMessageResponse.ErrorMessage.Builder, ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private Object session_ = "";
      /**
       * <code>optional string session = 2;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string session = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string session = 2;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 2;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <code>optional string session = 2;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 3;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 3;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <code>optional int64 company_id = 4;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional int64 company_id = 4;</code>
       */
      public Builder setCompanyId(long value) {
        
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 company_id = 4;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private long officeId_ ;
      /**
       * <code>optional int64 office_id = 5;</code>
       */
      public long getOfficeId() {
        return officeId_;
      }
      /**
       * <code>optional int64 office_id = 5;</code>
       */
      public Builder setOfficeId(long value) {
        
        officeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 office_id = 5;</code>
       */
      public Builder clearOfficeId() {
        
        officeId_ = 0L;
        onChanged();
        return this;
      }

      private Object idCard_ = "";
      /**
       * <code>optional string id_card = 6;</code>
       */
      public String getIdCard() {
        Object ref = idCard_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idCard_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id_card = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIdCardBytes() {
        Object ref = idCard_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idCard_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id_card = 6;</code>
       */
      public Builder setIdCard(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_card = 6;</code>
       */
      public Builder clearIdCard() {
        
        idCard_ = getDefaultInstance().getIdCard();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_card = 6;</code>
       */
      public Builder setIdCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idCard_ = value;
        onChanged();
        return this;
      }

      private Object idFrontPicPath_ = "";
      /**
       * <code>optional string id_front_pic_path = 7;</code>
       */
      public String getIdFrontPicPath() {
        Object ref = idFrontPicPath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idFrontPicPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id_front_pic_path = 7;</code>
       */
      public com.google.protobuf.ByteString
          getIdFrontPicPathBytes() {
        Object ref = idFrontPicPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idFrontPicPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id_front_pic_path = 7;</code>
       */
      public Builder setIdFrontPicPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idFrontPicPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_front_pic_path = 7;</code>
       */
      public Builder clearIdFrontPicPath() {
        
        idFrontPicPath_ = getDefaultInstance().getIdFrontPicPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_front_pic_path = 7;</code>
       */
      public Builder setIdFrontPicPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idFrontPicPath_ = value;
        onChanged();
        return this;
      }

      private Object idBackPicPath_ = "";
      /**
       * <code>optional string id_back_pic_path = 8;</code>
       */
      public String getIdBackPicPath() {
        Object ref = idBackPicPath_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idBackPicPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id_back_pic_path = 8;</code>
       */
      public com.google.protobuf.ByteString
          getIdBackPicPathBytes() {
        Object ref = idBackPicPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idBackPicPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id_back_pic_path = 8;</code>
       */
      public Builder setIdBackPicPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idBackPicPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_back_pic_path = 8;</code>
       */
      public Builder clearIdBackPicPath() {
        
        idBackPicPath_ = getDefaultInstance().getIdBackPicPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id_back_pic_path = 8;</code>
       */
      public Builder setIdBackPicPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idBackPicPath_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>optional string password = 9;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string password = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 9;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 9;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 9;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 10;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 10;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 10;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 10;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object email_ = "";
      /**
       * <code>optional string email = 11;</code>
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 11;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private Object phone_ = "";
      /**
       * <code>optional string phone = 12;</code>
       */
      public String getPhone() {
        Object ref = phone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder setPhone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 12;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private Object mobile_ = "";
      /**
       * <code>optional string mobile = 13;</code>
       */
      public String getMobile() {
        Object ref = mobile_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string mobile = 13;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 13;</code>
       */
      public Builder setMobile(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 13;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 13;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>optional string address = 14;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string address = 14;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 14;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 14;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 14;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private Object photo_ = "";
      /**
       * <code>optional string photo = 15;</code>
       */
      public String getPhoto() {
        Object ref = photo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          photo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string photo = 15;</code>
       */
      public com.google.protobuf.ByteString
          getPhotoBytes() {
        Object ref = photo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          photo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string photo = 15;</code>
       */
      public Builder setPhoto(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string photo = 15;</code>
       */
      public Builder clearPhoto() {
        
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string photo = 15;</code>
       */
      public Builder setPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        photo_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional int32 sex = 16;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 16;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 16;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 17;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 17;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 17;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:LoginResponseMessage)
    private static final LoginResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginResponseMessage();
    }

    public static LoginResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponseMessage>() {
      public LoginResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginResponseMessage> getParserForType() {
      return PARSER;
    }

    public LoginResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023LoginResponse.proto\032\032ErrorMessageRespo" +
      "nse.proto\"\311\002\n\024LoginResponseMessage\022\037\n\010er" +
      "rorMsg\030\001 \001(\0132\r.ErrorMessage\022\017\n\007session\030\002" +
      " \001(\t\022\n\n\002id\030\003 \001(\003\022\022\n\ncompany_id\030\004 \001(\003\022\021\n\t" +
      "office_id\030\005 \001(\003\022\017\n\007id_card\030\006 \001(\t\022\031\n\021id_f" +
      "ront_pic_path\030\007 \001(\t\022\030\n\020id_back_pic_path\030" +
      "\010 \001(\t\022\020\n\010password\030\t \001(\t\022\014\n\004name\030\n \001(\t\022\r\n" +
      "\005email\030\013 \001(\t\022\r\n\005phone\030\014 \001(\t\022\016\n\006mobile\030\r " +
      "\001(\t\022\017\n\007address\030\016 \001(\t\022\r\n\005photo\030\017 \001(\t\022\013\n\003s" +
      "ex\030\020 \001(\005\022\013\n\003age\030\021 \001(\005B.\n\035com.yzh.rfidbik",
      "e.app.responseB\rLoginResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ErrorMessageResponse.getDescriptor(),
        }, assigner);
    internal_static_LoginResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponseMessage_descriptor,
        new String[] { "ErrorMsg", "Session", "Id", "CompanyId", "OfficeId", "IdCard", "IdFrontPicPath", "IdBackPicPath", "Password", "Name", "Email", "Phone", "Mobile", "Address", "Photo", "Sex", "Age", });
    ErrorMessageResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
