// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SysDictResponse.proto

package com.yzh.rfid.app.response;

public final class SysDictResponse {
  private SysDictResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysDictResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SysDictResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage> 
        getSysDictMessageList();
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    com.yzh.rfid.app.response.SysDict.SysDictMessage getSysDictMessage(int index);
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    int getSysDictMessageCount();
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    java.util.List<? extends com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder> 
        getSysDictMessageOrBuilderList();
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder getSysDictMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code SysDictResponseMessage}
   */
  public  static final class SysDictResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SysDictResponseMessage)
      SysDictResponseMessageOrBuilder {
    // Use SysDictResponseMessage.newBuilder() to construct.
    private SysDictResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysDictResponseMessage() {
      sysDictMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SysDictResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                sysDictMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.SysDict.SysDictMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              sysDictMessage_.add(
                  input.readMessage(com.yzh.rfid.app.response.SysDict.SysDictMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          sysDictMessage_ = java.util.Collections.unmodifiableList(sysDictMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.SysDictResponse.internal_static_SysDictResponseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.SysDictResponse.internal_static_SysDictResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.class, com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int SYSDICTMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage> sysDictMessage_;
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    public java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage> getSysDictMessageList() {
      return sysDictMessage_;
    }
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    public java.util.List<? extends com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder> 
        getSysDictMessageOrBuilderList() {
      return sysDictMessage_;
    }
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    public int getSysDictMessageCount() {
      return sysDictMessage_.size();
    }
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.SysDict.SysDictMessage getSysDictMessage(int index) {
      return sysDictMessage_.get(index);
    }
    /**
     * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
     */
    public com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder getSysDictMessageOrBuilder(
        int index) {
      return sysDictMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < sysDictMessage_.size(); i++) {
        output.writeMessage(2, sysDictMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < sysDictMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, sysDictMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage other = (com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getSysDictMessageList()
          .equals(other.getSysDictMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getSysDictMessageCount() > 0) {
        hash = (37 * hash) + SYSDICTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSysDictMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SysDictResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SysDictResponseMessage)
        com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.SysDictResponse.internal_static_SysDictResponseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.SysDictResponse.internal_static_SysDictResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.class, com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSysDictMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (sysDictMessageBuilder_ == null) {
          sysDictMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          sysDictMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.SysDictResponse.internal_static_SysDictResponseMessage_descriptor;
      }

      public com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage build() {
        com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage buildPartial() {
        com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage result = new com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (sysDictMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            sysDictMessage_ = java.util.Collections.unmodifiableList(sysDictMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.sysDictMessage_ = sysDictMessage_;
        } else {
          result.sysDictMessage_ = sysDictMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage) {
          return mergeFrom((com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage other) {
        if (other == com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (sysDictMessageBuilder_ == null) {
          if (!other.sysDictMessage_.isEmpty()) {
            if (sysDictMessage_.isEmpty()) {
              sysDictMessage_ = other.sysDictMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSysDictMessageIsMutable();
              sysDictMessage_.addAll(other.sysDictMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.sysDictMessage_.isEmpty()) {
            if (sysDictMessageBuilder_.isEmpty()) {
              sysDictMessageBuilder_.dispose();
              sysDictMessageBuilder_ = null;
              sysDictMessage_ = other.sysDictMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              sysDictMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSysDictMessageFieldBuilder() : null;
            } else {
              sysDictMessageBuilder_.addAllMessages(other.sysDictMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.rfid.app.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage> sysDictMessage_ =
        java.util.Collections.emptyList();
      private void ensureSysDictMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sysDictMessage_ = new java.util.ArrayList<com.yzh.rfid.app.response.SysDict.SysDictMessage>(sysDictMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.SysDict.SysDictMessage, com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder, com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder> sysDictMessageBuilder_;

      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage> getSysDictMessageList() {
        if (sysDictMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sysDictMessage_);
        } else {
          return sysDictMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public int getSysDictMessageCount() {
        if (sysDictMessageBuilder_ == null) {
          return sysDictMessage_.size();
        } else {
          return sysDictMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.SysDict.SysDictMessage getSysDictMessage(int index) {
        if (sysDictMessageBuilder_ == null) {
          return sysDictMessage_.get(index);
        } else {
          return sysDictMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder setSysDictMessage(
          int index, com.yzh.rfid.app.response.SysDict.SysDictMessage value) {
        if (sysDictMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSysDictMessageIsMutable();
          sysDictMessage_.set(index, value);
          onChanged();
        } else {
          sysDictMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder setSysDictMessage(
          int index, com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder builderForValue) {
        if (sysDictMessageBuilder_ == null) {
          ensureSysDictMessageIsMutable();
          sysDictMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          sysDictMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder addSysDictMessage(com.yzh.rfid.app.response.SysDict.SysDictMessage value) {
        if (sysDictMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSysDictMessageIsMutable();
          sysDictMessage_.add(value);
          onChanged();
        } else {
          sysDictMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder addSysDictMessage(
          int index, com.yzh.rfid.app.response.SysDict.SysDictMessage value) {
        if (sysDictMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSysDictMessageIsMutable();
          sysDictMessage_.add(index, value);
          onChanged();
        } else {
          sysDictMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder addSysDictMessage(
          com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder builderForValue) {
        if (sysDictMessageBuilder_ == null) {
          ensureSysDictMessageIsMutable();
          sysDictMessage_.add(builderForValue.build());
          onChanged();
        } else {
          sysDictMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder addSysDictMessage(
          int index, com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder builderForValue) {
        if (sysDictMessageBuilder_ == null) {
          ensureSysDictMessageIsMutable();
          sysDictMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          sysDictMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder addAllSysDictMessage(
          Iterable<? extends com.yzh.rfid.app.response.SysDict.SysDictMessage> values) {
        if (sysDictMessageBuilder_ == null) {
          ensureSysDictMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sysDictMessage_);
          onChanged();
        } else {
          sysDictMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder clearSysDictMessage() {
        if (sysDictMessageBuilder_ == null) {
          sysDictMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          sysDictMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public Builder removeSysDictMessage(int index) {
        if (sysDictMessageBuilder_ == null) {
          ensureSysDictMessageIsMutable();
          sysDictMessage_.remove(index);
          onChanged();
        } else {
          sysDictMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder getSysDictMessageBuilder(
          int index) {
        return getSysDictMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder getSysDictMessageOrBuilder(
          int index) {
        if (sysDictMessageBuilder_ == null) {
          return sysDictMessage_.get(index);  } else {
          return sysDictMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public java.util.List<? extends com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder> 
           getSysDictMessageOrBuilderList() {
        if (sysDictMessageBuilder_ != null) {
          return sysDictMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sysDictMessage_);
        }
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder addSysDictMessageBuilder() {
        return getSysDictMessageFieldBuilder().addBuilder(
            com.yzh.rfid.app.response.SysDict.SysDictMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder addSysDictMessageBuilder(
          int index) {
        return getSysDictMessageFieldBuilder().addBuilder(
            index, com.yzh.rfid.app.response.SysDict.SysDictMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SysDictMessage sysDictMessage = 2;</code>
       */
      public java.util.List<com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder> 
           getSysDictMessageBuilderList() {
        return getSysDictMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.rfid.app.response.SysDict.SysDictMessage, com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder, com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder> 
          getSysDictMessageFieldBuilder() {
        if (sysDictMessageBuilder_ == null) {
          sysDictMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.rfid.app.response.SysDict.SysDictMessage, com.yzh.rfid.app.response.SysDict.SysDictMessage.Builder, com.yzh.rfid.app.response.SysDict.SysDictMessageOrBuilder>(
                  sysDictMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          sysDictMessage_ = null;
        }
        return sysDictMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SysDictResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:SysDictResponseMessage)
    private static final com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage();
    }

    public static com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysDictResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<SysDictResponseMessage>() {
      public SysDictResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SysDictResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SysDictResponseMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SysDictResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.SysDictResponse.SysDictResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SysDictResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SysDictResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025SysDictResponse.proto\032\032ErrorMessageRes" +
      "ponse.proto\032\rSysDict.proto\"b\n\026SysDictRes" +
      "ponseMessage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMe" +
      "ssage\022\'\n\016sysDictMessage\030\002 \003(\0132\017.SysDictM" +
      "essageB0\n\035com.yzh.rfid.app.responseB" +
      "\017SysDictResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor(),
          com.yzh.rfid.app.response.SysDict.getDescriptor(),
        }, assigner);
    internal_static_SysDictResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SysDictResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SysDictResponseMessage_descriptor,
        new String[] { "ErrorMsg", "SysDictMessage", });
    com.yzh.rfid.app.response.ErrorMessageResponse.getDescriptor();
    com.yzh.rfid.app.response.SysDict.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
