// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemMessage.proto

package com.yzh.rfid.app.response;

public final class SystemMessage {
  private SystemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemMessageMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemMessageMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional int32 messageType = 2;</code>
     */
    int getMessageType();

    /**
     * <pre>
     *消息子类型
     * </pre>
     *
     * <code>optional int32 messageSubType = 3;</code>
     */
    int getMessageSubType();

    /**
     * <pre>
     *消息主题
     * </pre>
     *
     * <code>optional string messageSubject = 4;</code>
     */
    String getMessageSubject();
    /**
     * <pre>
     *消息主题
     * </pre>
     *
     * <code>optional string messageSubject = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageSubjectBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string messageDescription = 5;</code>
     */
    String getMessageDescription();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string messageDescription = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageDescriptionBytes();

    /**
     * <pre>
     *web enable
     * </pre>
     *
     * <code>optional string webEnable = 6;</code>
     */
    String getWebEnable();
    /**
     * <pre>
     *web enable
     * </pre>
     *
     * <code>optional string webEnable = 6;</code>
     */
    com.google.protobuf.ByteString
        getWebEnableBytes();

    /**
     * <pre>
     *bike app
     * </pre>
     *
     * <code>optional string bikeApp = 7;</code>
     */
    String getBikeApp();
    /**
     * <pre>
     *bike app
     * </pre>
     *
     * <code>optional string bikeApp = 7;</code>
     */
    com.google.protobuf.ByteString
        getBikeAppBytes();

    /**
     * <pre>
     *police app
     * </pre>
     *
     * <code>optional string policeApp = 8;</code>
     */
    String getPoliceApp();
    /**
     * <pre>
     *police app
     * </pre>
     *
     * <code>optional string policeApp = 8;</code>
     */
    com.google.protobuf.ByteString
        getPoliceAppBytes();

    /**
     * <pre>
     *device app
     * </pre>
     *
     * <code>optional string deviceApp = 9;</code>
     */
    String getDeviceApp();
    /**
     * <pre>
     *device app
     * </pre>
     *
     * <code>optional string deviceApp = 9;</code>
     */
    com.google.protobuf.ByteString
        getDeviceAppBytes();

    /**
     * <pre>
     *reference id
     * </pre>
     *
     * <code>optional int64 referenceId = 10;</code>
     */
    long getReferenceId();

    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>optional int64 createDate = 11;</code>
     */
    long getCreateDate();

    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>optional int64 updateDate = 12;</code>
     */
    long getUpdateDate();
  }
  /**
   * Protobuf type {@code SystemMessageMessage}
   */
  public  static final class SystemMessageMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SystemMessageMessage)
      SystemMessageMessageOrBuilder {
    // Use SystemMessageMessage.newBuilder() to construct.
    private SystemMessageMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemMessageMessage() {
      id_ = 0L;
      messageType_ = 0;
      messageSubType_ = 0;
      messageSubject_ = "";
      messageDescription_ = "";
      webEnable_ = "";
      bikeApp_ = "";
      policeApp_ = "";
      deviceApp_ = "";
      referenceId_ = 0L;
      createDate_ = 0L;
      updateDate_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SystemMessageMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              messageType_ = input.readInt32();
              break;
            }
            case 24: {

              messageSubType_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              messageSubject_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              messageDescription_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              webEnable_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              bikeApp_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              policeApp_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              deviceApp_ = s;
              break;
            }
            case 80: {

              referenceId_ = input.readInt64();
              break;
            }
            case 88: {

              createDate_ = input.readInt64();
              break;
            }
            case 96: {

              updateDate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.rfid.app.response.SystemMessage.internal_static_SystemMessageMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.rfid.app.response.SystemMessage.internal_static_SystemMessageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.class, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional int32 messageType = 2;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGESUBTYPE_FIELD_NUMBER = 3;
    private int messageSubType_;
    /**
     * <pre>
     *消息子类型
     * </pre>
     *
     * <code>optional int32 messageSubType = 3;</code>
     */
    public int getMessageSubType() {
      return messageSubType_;
    }

    public static final int MESSAGESUBJECT_FIELD_NUMBER = 4;
    private volatile Object messageSubject_;
    /**
     * <pre>
     *消息主题
     * </pre>
     *
     * <code>optional string messageSubject = 4;</code>
     */
    public String getMessageSubject() {
      Object ref = messageSubject_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageSubject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息主题
     * </pre>
     *
     * <code>optional string messageSubject = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageSubjectBytes() {
      Object ref = messageSubject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageSubject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEDESCRIPTION_FIELD_NUMBER = 5;
    private volatile Object messageDescription_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string messageDescription = 5;</code>
     */
    public String getMessageDescription() {
      Object ref = messageDescription_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageDescription_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional string messageDescription = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageDescriptionBytes() {
      Object ref = messageDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEBENABLE_FIELD_NUMBER = 6;
    private volatile Object webEnable_;
    /**
     * <pre>
     *web enable
     * </pre>
     *
     * <code>optional string webEnable = 6;</code>
     */
    public String getWebEnable() {
      Object ref = webEnable_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        webEnable_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *web enable
     * </pre>
     *
     * <code>optional string webEnable = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWebEnableBytes() {
      Object ref = webEnable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        webEnable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKEAPP_FIELD_NUMBER = 7;
    private volatile Object bikeApp_;
    /**
     * <pre>
     *bike app
     * </pre>
     *
     * <code>optional string bikeApp = 7;</code>
     */
    public String getBikeApp() {
      Object ref = bikeApp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bikeApp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *bike app
     * </pre>
     *
     * <code>optional string bikeApp = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBikeAppBytes() {
      Object ref = bikeApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bikeApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POLICEAPP_FIELD_NUMBER = 8;
    private volatile Object policeApp_;
    /**
     * <pre>
     *police app
     * </pre>
     *
     * <code>optional string policeApp = 8;</code>
     */
    public String getPoliceApp() {
      Object ref = policeApp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        policeApp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *police app
     * </pre>
     *
     * <code>optional string policeApp = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPoliceAppBytes() {
      Object ref = policeApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        policeApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEAPP_FIELD_NUMBER = 9;
    private volatile Object deviceApp_;
    /**
     * <pre>
     *device app
     * </pre>
     *
     * <code>optional string deviceApp = 9;</code>
     */
    public String getDeviceApp() {
      Object ref = deviceApp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceApp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *device app
     * </pre>
     *
     * <code>optional string deviceApp = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceAppBytes() {
      Object ref = deviceApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCEID_FIELD_NUMBER = 10;
    private long referenceId_;
    /**
     * <pre>
     *reference id
     * </pre>
     *
     * <code>optional int64 referenceId = 10;</code>
     */
    public long getReferenceId() {
      return referenceId_;
    }

    public static final int CREATEDATE_FIELD_NUMBER = 11;
    private long createDate_;
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>optional int64 createDate = 11;</code>
     */
    public long getCreateDate() {
      return createDate_;
    }

    public static final int UPDATEDATE_FIELD_NUMBER = 12;
    private long updateDate_;
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>optional int64 updateDate = 12;</code>
     */
    public long getUpdateDate() {
      return updateDate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (messageType_ != 0) {
        output.writeInt32(2, messageType_);
      }
      if (messageSubType_ != 0) {
        output.writeInt32(3, messageSubType_);
      }
      if (!getMessageSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageSubject_);
      }
      if (!getMessageDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messageDescription_);
      }
      if (!getWebEnableBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, webEnable_);
      }
      if (!getBikeAppBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, bikeApp_);
      }
      if (!getPoliceAppBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, policeApp_);
      }
      if (!getDeviceAppBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deviceApp_);
      }
      if (referenceId_ != 0L) {
        output.writeInt64(10, referenceId_);
      }
      if (createDate_ != 0L) {
        output.writeInt64(11, createDate_);
      }
      if (updateDate_ != 0L) {
        output.writeInt64(12, updateDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageType_);
      }
      if (messageSubType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messageSubType_);
      }
      if (!getMessageSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageSubject_);
      }
      if (!getMessageDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messageDescription_);
      }
      if (!getWebEnableBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, webEnable_);
      }
      if (!getBikeAppBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, bikeApp_);
      }
      if (!getPoliceAppBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, policeApp_);
      }
      if (!getDeviceAppBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deviceApp_);
      }
      if (referenceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, referenceId_);
      }
      if (createDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, createDate_);
      }
      if (updateDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, updateDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage)) {
        return super.equals(obj);
      }
      com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage other = (com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getMessageType()
          == other.getMessageType());
      result = result && (getMessageSubType()
          == other.getMessageSubType());
      result = result && getMessageSubject()
          .equals(other.getMessageSubject());
      result = result && getMessageDescription()
          .equals(other.getMessageDescription());
      result = result && getWebEnable()
          .equals(other.getWebEnable());
      result = result && getBikeApp()
          .equals(other.getBikeApp());
      result = result && getPoliceApp()
          .equals(other.getPoliceApp());
      result = result && getDeviceApp()
          .equals(other.getDeviceApp());
      result = result && (getReferenceId()
          == other.getReferenceId());
      result = result && (getCreateDate()
          == other.getCreateDate());
      result = result && (getUpdateDate()
          == other.getUpdateDate());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + MESSAGESUBTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageSubType();
      hash = (37 * hash) + MESSAGESUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageSubject().hashCode();
      hash = (37 * hash) + MESSAGEDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getMessageDescription().hashCode();
      hash = (37 * hash) + WEBENABLE_FIELD_NUMBER;
      hash = (53 * hash) + getWebEnable().hashCode();
      hash = (37 * hash) + BIKEAPP_FIELD_NUMBER;
      hash = (53 * hash) + getBikeApp().hashCode();
      hash = (37 * hash) + POLICEAPP_FIELD_NUMBER;
      hash = (53 * hash) + getPoliceApp().hashCode();
      hash = (37 * hash) + DEVICEAPP_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceApp().hashCode();
      hash = (37 * hash) + REFERENCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReferenceId());
      hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDate());
      hash = (37 * hash) + UPDATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SystemMessageMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemMessageMessage)
        com.yzh.rfid.app.response.SystemMessage.SystemMessageMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.rfid.app.response.SystemMessage.internal_static_SystemMessageMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.rfid.app.response.SystemMessage.internal_static_SystemMessageMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.class, com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.Builder.class);
      }

      // Construct using com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        messageType_ = 0;

        messageSubType_ = 0;

        messageSubject_ = "";

        messageDescription_ = "";

        webEnable_ = "";

        bikeApp_ = "";

        policeApp_ = "";

        deviceApp_ = "";

        referenceId_ = 0L;

        createDate_ = 0L;

        updateDate_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.rfid.app.response.SystemMessage.internal_static_SystemMessageMessage_descriptor;
      }

      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getDefaultInstanceForType() {
        return com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.getDefaultInstance();
      }

      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage build() {
        com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage buildPartial() {
        com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage result = new com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage(this);
        result.id_ = id_;
        result.messageType_ = messageType_;
        result.messageSubType_ = messageSubType_;
        result.messageSubject_ = messageSubject_;
        result.messageDescription_ = messageDescription_;
        result.webEnable_ = webEnable_;
        result.bikeApp_ = bikeApp_;
        result.policeApp_ = policeApp_;
        result.deviceApp_ = deviceApp_;
        result.referenceId_ = referenceId_;
        result.createDate_ = createDate_;
        result.updateDate_ = updateDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage) {
          return mergeFrom((com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage other) {
        if (other == com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getMessageSubType() != 0) {
          setMessageSubType(other.getMessageSubType());
        }
        if (!other.getMessageSubject().isEmpty()) {
          messageSubject_ = other.messageSubject_;
          onChanged();
        }
        if (!other.getMessageDescription().isEmpty()) {
          messageDescription_ = other.messageDescription_;
          onChanged();
        }
        if (!other.getWebEnable().isEmpty()) {
          webEnable_ = other.webEnable_;
          onChanged();
        }
        if (!other.getBikeApp().isEmpty()) {
          bikeApp_ = other.bikeApp_;
          onChanged();
        }
        if (!other.getPoliceApp().isEmpty()) {
          policeApp_ = other.policeApp_;
          onChanged();
        }
        if (!other.getDeviceApp().isEmpty()) {
          deviceApp_ = other.deviceApp_;
          onChanged();
        }
        if (other.getReferenceId() != 0L) {
          setReferenceId(other.getReferenceId());
        }
        if (other.getCreateDate() != 0L) {
          setCreateDate(other.getCreateDate());
        }
        if (other.getUpdateDate() != 0L) {
          setUpdateDate(other.getUpdateDate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional int32 messageType = 2;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional int32 messageType = 2;</code>
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional int32 messageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int messageSubType_ ;
      /**
       * <pre>
       *消息子类型
       * </pre>
       *
       * <code>optional int32 messageSubType = 3;</code>
       */
      public int getMessageSubType() {
        return messageSubType_;
      }
      /**
       * <pre>
       *消息子类型
       * </pre>
       *
       * <code>optional int32 messageSubType = 3;</code>
       */
      public Builder setMessageSubType(int value) {
        
        messageSubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息子类型
       * </pre>
       *
       * <code>optional int32 messageSubType = 3;</code>
       */
      public Builder clearMessageSubType() {
        
        messageSubType_ = 0;
        onChanged();
        return this;
      }

      private Object messageSubject_ = "";
      /**
       * <pre>
       *消息主题
       * </pre>
       *
       * <code>optional string messageSubject = 4;</code>
       */
      public String getMessageSubject() {
        Object ref = messageSubject_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageSubject_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息主题
       * </pre>
       *
       * <code>optional string messageSubject = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageSubjectBytes() {
        Object ref = messageSubject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageSubject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息主题
       * </pre>
       *
       * <code>optional string messageSubject = 4;</code>
       */
      public Builder setMessageSubject(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageSubject_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息主题
       * </pre>
       *
       * <code>optional string messageSubject = 4;</code>
       */
      public Builder clearMessageSubject() {
        
        messageSubject_ = getDefaultInstance().getMessageSubject();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息主题
       * </pre>
       *
       * <code>optional string messageSubject = 4;</code>
       */
      public Builder setMessageSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageSubject_ = value;
        onChanged();
        return this;
      }

      private Object messageDescription_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string messageDescription = 5;</code>
       */
      public String getMessageDescription() {
        Object ref = messageDescription_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageDescription_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string messageDescription = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageDescriptionBytes() {
        Object ref = messageDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string messageDescription = 5;</code>
       */
      public Builder setMessageDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string messageDescription = 5;</code>
       */
      public Builder clearMessageDescription() {
        
        messageDescription_ = getDefaultInstance().getMessageDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional string messageDescription = 5;</code>
       */
      public Builder setMessageDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageDescription_ = value;
        onChanged();
        return this;
      }

      private Object webEnable_ = "";
      /**
       * <pre>
       *web enable
       * </pre>
       *
       * <code>optional string webEnable = 6;</code>
       */
      public String getWebEnable() {
        Object ref = webEnable_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          webEnable_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *web enable
       * </pre>
       *
       * <code>optional string webEnable = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWebEnableBytes() {
        Object ref = webEnable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          webEnable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *web enable
       * </pre>
       *
       * <code>optional string webEnable = 6;</code>
       */
      public Builder setWebEnable(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        webEnable_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *web enable
       * </pre>
       *
       * <code>optional string webEnable = 6;</code>
       */
      public Builder clearWebEnable() {
        
        webEnable_ = getDefaultInstance().getWebEnable();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *web enable
       * </pre>
       *
       * <code>optional string webEnable = 6;</code>
       */
      public Builder setWebEnableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        webEnable_ = value;
        onChanged();
        return this;
      }

      private Object bikeApp_ = "";
      /**
       * <pre>
       *bike app
       * </pre>
       *
       * <code>optional string bikeApp = 7;</code>
       */
      public String getBikeApp() {
        Object ref = bikeApp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bikeApp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *bike app
       * </pre>
       *
       * <code>optional string bikeApp = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBikeAppBytes() {
        Object ref = bikeApp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bikeApp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *bike app
       * </pre>
       *
       * <code>optional string bikeApp = 7;</code>
       */
      public Builder setBikeApp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bikeApp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bike app
       * </pre>
       *
       * <code>optional string bikeApp = 7;</code>
       */
      public Builder clearBikeApp() {
        
        bikeApp_ = getDefaultInstance().getBikeApp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bike app
       * </pre>
       *
       * <code>optional string bikeApp = 7;</code>
       */
      public Builder setBikeAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bikeApp_ = value;
        onChanged();
        return this;
      }

      private Object policeApp_ = "";
      /**
       * <pre>
       *police app
       * </pre>
       *
       * <code>optional string policeApp = 8;</code>
       */
      public String getPoliceApp() {
        Object ref = policeApp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          policeApp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *police app
       * </pre>
       *
       * <code>optional string policeApp = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPoliceAppBytes() {
        Object ref = policeApp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          policeApp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *police app
       * </pre>
       *
       * <code>optional string policeApp = 8;</code>
       */
      public Builder setPoliceApp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        policeApp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *police app
       * </pre>
       *
       * <code>optional string policeApp = 8;</code>
       */
      public Builder clearPoliceApp() {
        
        policeApp_ = getDefaultInstance().getPoliceApp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *police app
       * </pre>
       *
       * <code>optional string policeApp = 8;</code>
       */
      public Builder setPoliceAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        policeApp_ = value;
        onChanged();
        return this;
      }

      private Object deviceApp_ = "";
      /**
       * <pre>
       *device app
       * </pre>
       *
       * <code>optional string deviceApp = 9;</code>
       */
      public String getDeviceApp() {
        Object ref = deviceApp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceApp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *device app
       * </pre>
       *
       * <code>optional string deviceApp = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceAppBytes() {
        Object ref = deviceApp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceApp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *device app
       * </pre>
       *
       * <code>optional string deviceApp = 9;</code>
       */
      public Builder setDeviceApp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceApp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *device app
       * </pre>
       *
       * <code>optional string deviceApp = 9;</code>
       */
      public Builder clearDeviceApp() {
        
        deviceApp_ = getDefaultInstance().getDeviceApp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *device app
       * </pre>
       *
       * <code>optional string deviceApp = 9;</code>
       */
      public Builder setDeviceAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceApp_ = value;
        onChanged();
        return this;
      }

      private long referenceId_ ;
      /**
       * <pre>
       *reference id
       * </pre>
       *
       * <code>optional int64 referenceId = 10;</code>
       */
      public long getReferenceId() {
        return referenceId_;
      }
      /**
       * <pre>
       *reference id
       * </pre>
       *
       * <code>optional int64 referenceId = 10;</code>
       */
      public Builder setReferenceId(long value) {
        
        referenceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *reference id
       * </pre>
       *
       * <code>optional int64 referenceId = 10;</code>
       */
      public Builder clearReferenceId() {
        
        referenceId_ = 0L;
        onChanged();
        return this;
      }

      private long createDate_ ;
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 11;</code>
       */
      public long getCreateDate() {
        return createDate_;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 11;</code>
       */
      public Builder setCreateDate(long value) {
        
        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *创建时间
       * </pre>
       *
       * <code>optional int64 createDate = 11;</code>
       */
      public Builder clearCreateDate() {
        
        createDate_ = 0L;
        onChanged();
        return this;
      }

      private long updateDate_ ;
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 12;</code>
       */
      public long getUpdateDate() {
        return updateDate_;
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 12;</code>
       */
      public Builder setUpdateDate(long value) {
        
        updateDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新时间
       * </pre>
       *
       * <code>optional int64 updateDate = 12;</code>
       */
      public Builder clearUpdateDate() {
        
        updateDate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SystemMessageMessage)
    }

    // @@protoc_insertion_point(class_scope:SystemMessageMessage)
    private static final com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage();
    }

    public static com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SystemMessageMessage>
        PARSER = new com.google.protobuf.AbstractParser<SystemMessageMessage>() {
      public SystemMessageMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SystemMessageMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemMessageMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SystemMessageMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.rfid.app.response.SystemMessage.SystemMessageMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemMessageMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemMessageMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023SystemMessage.proto\"\212\002\n\024SystemMessageM" +
      "essage\022\n\n\002id\030\001 \001(\003\022\023\n\013messageType\030\002 \001(\005\022" +
      "\026\n\016messageSubType\030\003 \001(\005\022\026\n\016messageSubjec" +
      "t\030\004 \001(\t\022\032\n\022messageDescription\030\005 \001(\t\022\021\n\tw" +
      "ebEnable\030\006 \001(\t\022\017\n\007bikeApp\030\007 \001(\t\022\021\n\tpolic" +
      "eApp\030\010 \001(\t\022\021\n\tdeviceApp\030\t \001(\t\022\023\n\013referen" +
      "ceId\030\n \001(\003\022\022\n\ncreateDate\030\013 \001(\003\022\022\n\nupdate" +
      "Date\030\014 \001(\003B.\n\035com.yzh.rfid.app.respo" +
      "nseB\rSystemMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SystemMessageMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SystemMessageMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemMessageMessage_descriptor,
        new String[] { "Id", "MessageType", "MessageSubType", "MessageSubject", "MessageDescription", "WebEnable", "BikeApp", "PoliceApp", "DeviceApp", "ReferenceId", "CreateDate", "UpdateDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
